### ISSUE TITLE
amp-carousel version currently incorrect

### ISSUE THREAD

**Issue by morsssss** [garanj/amphtml-autoscript#2]
`amp-carousel` v2 is coming! The files are already listed in [this manifest](https://api.github.com/repos/ampproject/amphtml/git/trees/master?recursive=1). But the new JS isn't on the CDN yet or whitelisted by the validator. So this plugin, which we've found so wondrous and useful, now tries to load a JS that doesn't exist, and the validator complains about it too. 😭 

@choumx points out that all the scraping is doing is getting the version that the `-latest` suffix would pull anyway, except that it's more fragile. But we do want to allow people to choose their favorite version of a given component. So I'd suggest the following:

* use "latest" by default
* allow a config JSON that could pin any component to a specific version number, which was a feature we wanted originally anyway

This would mean we could lose the scraping.

WDYT?

**Comment by garanj** [comment]
This was fixed in v 1.5.0 with [local version overides](https://www.npmjs.com/package/amphtml-autoscript#local-component-version-overrides).
